name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  what:
    runs-on: self-hosted
    steps:
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
        - run: docker --log-level=debug run --detach --privileged --userns=host --pid=host --mount type=bind,src=/tmp,dst=/tmp --mount type=bind,src=/nix,dst=/nix --mount type=bind,src=/etc,dst=/etc,readonly --restart always --init determinate-nix-shim:latest
